plugins:
  ################## 数据源 ################
  - tag: geoip_private # 私网 IP
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rules/geoip_private.txt"
  - tag: geoip_cn # 中国 IP
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rules/geoip_cn.txt"

  - tag: geosite_cn # 中国域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_cn.txt"
  - tag: geosite_gfw # GFW 域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_gfw.txt"
  - tag: geosite_location-!cn # 非中国域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_geolocation-!cn.txt"
  - tag: geosite_ads-all # 广告域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_category-ads-all.txt"

  ################# 可执行插件 ################

  # 缓存 LAN
  - tag: cache_lan
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 86400
  # 缓存 WAN
  - tag: cache_wan
    type: cache
    args:
      size: 131072
      lazy_cache_ttl: 86400

  # 无 ECS 信息
  - tag: no_ecs
    type: ecs_handler
    args:
      forward: true # 是否转发来自下游的 ECS
      preset: "" # 发送预设 ECS
      send: false # 是否发送 ECS
      mask4: 24
      mask6: 48 
  
  # 附加 ECS CN 信息
  - tag: ecs_cn
    type: ecs_handler
    args:
      forward: true # 是否转发来自下游的 ECS
      preset: 45.207.213.35 # 发送预设 ECS
      send: true # 是否发送 ECS
      mask4: 24 # IPv4 掩码。默认 24
      mask6: 48 # IPv6 掩码。默认 48

  # 调整 TTL
  - tag: ttl_1m
    type: sequence
    args:
      - exec: ttl 60
  - tag: ttl_5m
    type: sequence
    args:
      - exec: ttl 300
  - tag: ttl_1h
    type: sequence
    args:
      - exec: ttl 3600

  ################# DNS #################
  # Cloudflare DoH DoT H3
  - tag: cloudflare
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://1.1.1.1/dns-query"
          dial_addr: "1.1.1.1"
        - addr: "tls://1.1.1.1"
          dial_addr: "2606:4700:4700::1111"
          enable_pipeline: true
        - addr: "tls://1.1.1.1"
          dial_addr: "1.1.1.1"
          enable_pipeline: true

  - tag: quad9
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://dns11.quad9.net/dns-query"
          dial_addr: "149.112.112.112"
        - addr: "https://dns11.quad9.net/dns-query"
          dial_addr: "2620:fe::fe"
        - addr: "tls://dns11.quad9.net"
          dial_addr: "149.112.112.9"
          enable_pipeline: true
        - addr: "tls://dns11.quad9.net"
          dial_addr: "2620:fe::9"
          enable_pipeline: true

  - tag: forward_remote
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://1.1.1.1/dns-query"
          dial_addr: "1.1.1.1"
        - addr: "https://dns.quad9.net/dns-query"
          dial_addr: "9.9.9.9"
        - addr: "https://1.0.0.1/dns-query"
          dial_addr: "2606:4700:4700::1111"
        - addr: "https://unfiltered.adguard-dns.com/dns-query"
          dial_addr: "1.0.0.1"

  # 阿里 DoH DoT H3
  - tag: ali
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.6.6.6"
        - addr: "tls://dns.alidns.com"
          dial_addr: "2400:3200:baba::1"
          enable_pipeline: true
        - addr: "tls://dns.alidns.com"
          dial_addr: "223.5.5.5"
          enable_pipeline: true
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          enable_http3: true
        - addr: "https://dns.alidns.com/dns-query"
          dial_addr: "2400:3200::1"
          enable_http3: true

  # DNSPod DoH DoT
  - tag: dnspod
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://doh.pub/dns-query"
          dial_addr: "119.29.29.29"
        - addr: "https://doh.pub/dns-query"
          dial_addr: "119.28.28.28"
        - addr: "tls://doh.pub"
          dial_addr: "119.29.29.29"
          enable_pipeline: true
        - addr: "tls://doh.pub"
          dial_addr: "119.28.28.28"
          enable_pipeline: true

  # 360 DoH DoT
  - tag: 360
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://doh.360.cn/dns-query"
          dial_addr: "101.226.4.6"
        - addr: "https://doh.360.cn/dns-query"
          dial_addr: "218.30.118.6"
        - addr: "tls://doh.360.cn"
          dial_addr: "101.226.4.6"
          enable_pipeline: true
        - addr: "tls://doh.360.cn"
          dial_addr: "218.30.118.6"
          enable_pipeline: true

  ################# 序列 #################
  - tag: dns_nocn
    type: "fallback"
    args:
      primary: cloudflare # 主 DNS
      secondary: quad9 # 备用 DNS
      threshold: 700 # 无响应切换 毫秒
      always_standby: true # 副可执行插件始终待命
  
  # DNS-CN 序列
  - tag: dns_cn
    type: "fallback"
    args:
      primary: ali # 主 DNS
      secondary: dnspod # 备用 DNS
      threshold: 700
      always_standby: true # 副可执行插件始终待命

  - tag: dns_nocn_seq
    type: sequence
    args:
      - exec: query_summary dns_nocn
      - exec: $ecs_cn
      - exec: $dns_nocn

  - tag: dns_cn_seq
    type: sequence
    args:
      - exec: query_summary dns_cn
      - exec: $no_ecs
      - exec: $dns_cn

  - tag: local_seq
    type: sequence
    args:
      - exec: query_summary local
      - exec: $local

  - tag: fallback_seq # 其他特殊情况统一使用 DNS-CN 处理
    type: sequence
    args:
      - exec: query_summary fallback
      - exec: $dns_cn

  - tag: other_seq # 其他特殊情况统一使用 DNS-CN 处理
    type: sequence
    args:
      - exec: query_summary other
      - exec: $dns_cn

  - tag: query_gfw
    type: sequence
    args:
      - exec: $forward_remote

  # Query Fallback
  - tag: query_fallback
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $fallback_seq

  # Query LAN
  - tag: query_lan
    type: sequence
    args:
      - exec: $cache_lan
      - matches: has_resp # 命中了 LAN Cache
        exec: return
      - exec: $local_seq

  # 其他所有情况
  - tag: query_other 
    type: sequence
    args:
      - exec: $other_seq

  - tag: pre_handle
    type: sequence
    args:
      - exec: $ttl_1h # TTL 1h
      - exec: accept # 接受响应,终止流程

  - tag: main_handle
    type: sequence
    args:
      - exec: $ttl_5m # TTL 5min
      - exec: accept # 接受响应,终止流程

  # Pre Sequence 结果处理 
  - tag: has_resp_pre
    type: sequence
    args:
      - matches: has_resp # 如果 Pre 序列已有响应
        exec: goto pre_handle

  # Main Sequence 结果处理
  - tag: has_resp_main
    type: sequence
    args:
      - matches: has_resp
        exec: goto main_handle

  # Pre Sequence
  - tag: pre_sequence
    type: sequence
    args:
      - matches: qtype 65 # TYPE 65 类型|DNS服务器状态
        exec: $reject_qtype65
      - matches: "qname keyword::" # 无效域名
        exec: $reject_null_domain
      - matches: qtype 12 # TYPE 12 类型|反查域名 PTR 记录
        exec: $query_other
      - matches: qtype 255 # TYPE 255 类型|DNS服务器拓展支持
        exec: $query_other
      - matches: ptr_ip $geoip_private # Private IP
        exec: $query_lan
      - exec: jump has_resp_pre

  # Main Sequence
  - tag: main_sequence
    type: sequence
    args:
      - matches: qname $geosite_ads-all # 广告域名
        exec: $reject_ad
      - exec: $cache_wan # Cache WAN
      - exec: jump has_resp_main
      # 其他
      - exec: $no_ecs
      - exec: $query_fallback
      - exec: jump has_resp_main

  - tag: sequence
    type: sequence
    args:
      - exec: metrics_collector metrics
      - exec: $pre_sequence # 预处理
      - exec: $main_sequence # 主执行序列

  # 在同一端口启动 UDP 和 TCP 服务器。
  - type: udp_server
    args:
      entry: sequence
      listen: :53
  - type: tcp_server
    args:
      entry: sequence
      listen: :53