include:
  - "/etc/mosdns/rules"

plugins:
  ################## 数据源 ################
  - tag: geoip_private # 私网IP
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_private.txt"
  - tag: geoip_cn # 中国IP
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"
  - tag: geosite_cn # 中国域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/geosite_cn.txt"
  - tag: geosite_gfw # GFW域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_gfw.txt"
  - tag: geosite_location-!cn # 非中国域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/geosite_geolocation-!cn.txt"
  - tag: geosite_ads-all # 广告域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/geosite_category-ads-all.txt"

  ################## 可执行插件 ################
  - tag: cache_lan
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 86400
  - tag: cache_wan
    type: cache
    args:
      size: 131072
      lazy_cache_ttl: 86400
  - tag: no_ecs
    type: ecs_handler
    args:
      forward: false
      preset: ""
      send: false
      mask4: 24
      mask6: 48
  - tag: ecs_cn
    type: ecs_handler
    args:
      forward: false
      preset: "114.217.98.237"
      send: false
      mask4: 24
      mask6: 48
  - tag: ttl_1m
    type: sequence
    args:
      - exec: ttl 60
  - tag: ttl_5m
    type: sequence
    args:
      - exec: ttl 300
  - tag: ttl_1h
    type: sequence
    args:
      - exec: ttl 3600

  ################## DNS解析序列 ################
  - tag: reject_null_domain
    type: sequence
    args:
      - exec: query_summary reject_null_domain
      - exec: $reject_3
  - tag: reject_qtype65
    type: sequence
    args:
      - exec: query_summary reject_qtype65
      - exec: $reject_3
  - tag: reject_ad
    type: sequence
    args:
      - exec: query_summary reject_adlist
      - exec: $reject_3

  - tag: dns_nocn
    type: fallback
    args:
      primary: quad9
      secondary: nextdns
      threshold: 700
      always_standby: true
  - tag: dns_cn
    type: fallback
    args:
      primary: ali
      secondary: dnspod
      threshold: 500
      always_standby: true

  - tag: dns_nocn_seq
    type: sequence
    args:
      - exec: query_summary dns_nocn
      - exec: $dns_nocn
  - tag: dns_cn_seq
    type: sequence
    args:
      - exec: query_summary dns_cn
      - exec: $dns_cn
  - tag: local_seq
    type: sequence
    args:
      - exec: query_summary local
      - exec: $local
  - tag: fallback_seq
    type: sequence
    args:
      - exec: query_summary fallback
      - exec: $dns_cn
  - tag: other_seq
    type: sequence
    args:
      - exec: query_summary other
      - exec: $dns_cn

  - tag: query_cn
    type: sequence
    args:
      - exec: $ecs_cn
      - exec: $dns_cn_seq
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp
  - tag: query_nocn
    type: sequence
    args:
      - exec: $no_ecs
      - exec: prefer_ipv4
      - exec: $dns_nocn_seq
      - matches: "resp_ip $geoip_cn"
        exec: drop_resp
  - tag: query_gfw
    type: sequence
    args:
      - exec: $forward_remote
  - tag: query_fallback
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $fallback_seq
  - tag: query_lan
    type: sequence
    args:
      - exec: $cache_lan
      - matches: has_resp
        exec: return
      - exec: $local_seq
  - tag: query_other
    type: sequence
    args:
      - exec: $other_seq

  - tag: pre_handle
    type: sequence
    args:
      - exec: $ttl_1h
      - exec: accept
  - tag: main_handle
    type: sequence
    args:
      - exec: $ttl_5m
      - exec: accept

  - tag: has_resp_pre
    type: sequence
    args:
      - matches: has_resp
        exec: goto pre_handle
  - tag: has_resp_main
    type: sequence
    args:
      - matches: has_resp
        exec: goto main_handle

  - tag: pre_sequence
    type: sequence
    args:
      - matches: qtype 65
        exec: $reject_qtype65
      - matches: "qname keyword::"
        exec: $reject_null_domain
      - matches: qtype 12
        exec: $query_other
      - matches: qtype 255
        exec: $query_other
      - matches: ptr_ip $geoip_private
        exec: $query_lan
      - exec: jump has_resp_pre

  - tag: main_sequence
    type: sequence
    args:
      - matches: qname $geosite_ads-all
        exec: $reject_ad
      - exec: $cache_wan
      - exec: jump has_resp_main
      - matches: qname $geosite_cn
        exec: $query_cn
      - exec: jump has_resp_main
      - matches: qname $geosite_gfw
        exec: $query_gfw
      - exec: jump has_resp_main
      - matches: qname $geosite_location-!cn
        exec: $query_nocn
      - exec: jump has_resp_main
      - exec: $no_ecs
      - exec: $query_fallback
      - exec: jump has_resp_main

  - tag: sequence
    type: sequence
    args:
      - exec: metrics_collector metrics
      - exec: $pre_sequence
      - exec: $main_sequence

  # 在同一端口启动 UDP 和 TCP 服务器。
  - type: udp_server
    args:
      entry: sequence
      listen: :53
  - type: tcp_server
    args:
      entry: sequence
      listen: :53