plugins:
  ################# 预加载插件 ################
  - tag: ttl_1m
    type: sequence
    args:
      - exec: ttl 60

  - tag: ttl_5m
    type: sequence
    args:
      - exec: ttl 300

  - tag: ttl_1h
    type: sequence
    args:
      - exec: ttl 3600

  - tag: ecs
    type: ecs_handler
    args:
      forward: false
      preset: 45.207.213.35
      send: false
      mask4: 24
      mask6: 48

  - tag: cache_lan
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 86400

  - tag: cache_wan
    type: cache
    args:
      size: 131072
      lazy_cache_ttl: 86400

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - /etc/mosdns/rules/geoip_cn.txt

  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - /etc/mosdns/rules/geosite_cn.txt

  - tag: geosite_gfw
    type: domain_set
    args:
      files:
        - /etc/mosdns/rules/geosite_gfw.txt

  - tag: geosite_location-!cn
    type: domain_set
    args:
      files:
        - /etc/mosdns/rules/geosite_geolocation-!cn.txt

  - tag: geosite_ads-all
    type: domain_set
    args:
      files:
        - /etc/mosdns/rules/geosite_category-ads-all.txt

  - tag: alidnsdnspod
    type: forward
    args:
      concurrent: 2  # 减少并发查询数
      upstreams:
        - addr: "udp://223.5.5.5"
        - addr: "udp://223.6.6.6"
        - addr: "udp://119.29.29.29"
        - addr: "udp://119.28.28.28"

  - tag: trafficroute
    type: forward
    args:
      concurrent: 1  # 减少并发查询数
      upstreams:
        - addr: "udp://180.184.1.1"
        - addr: "udp://180.184.2.2"

  - tag: quad9
    type: forward
    args:
      concurrent: 1  # 减少并发查询数
      upstreams:
        - addr: "udp://9.9.9.10"
        - addr: "udp://149.112.112.10"

  - tag: cleanbrowsing
    type: forward
    args:
      concurrent: 1  # 减少并发查询数
      upstreams:
        - addr: "udp://185.228.168.168"
        - addr: "udp://185.228.169.168"

  ################# DNS #################
  - tag: dns_nocn
    type: fallback
    args:
      primary: cleanbrowsing
      secondary: quad9
      threshold: 900
      always_standby: true

  - tag: dns_cn
    type: fallback
    args:
      primary: alidnsdnspod
      secondary: trafficroute
      threshold: 300
      always_standby: true

  ################# 执行策略 ################
  - tag: dns_nocn_seq
    type: sequence
    args:
      - exec: query_summary dns_nocn
      - exec: $dns_nocn

  - tag: dns_cn_seq
    type: sequence
    args:
      - exec: query_summary dns_cn
      - exec: $dns_cn

  - tag: local_seq
    type: sequence
    args:
      - exec: query_summary dns_cn
      - exec: $dns_cn

  - tag: fallback_seq
    type: sequence
    args:
      - exec: query_summary fallback
      - exec: $dns_cn

  - tag: other_seq
    type: sequence
    args:
      - exec: query_summary other
      - exec: $dns_cn

  - tag: query_cn
    type: sequence
    args:
      - exec: $ecs
      - exec: $dns_cn_seq
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  - tag: query_nocn
    type: sequence
    args:
      - exec: $ecs
      - exec: prefer_ipv4
      - exec: $dns_nocn_seq
      - matches: resp_ip $geoip_cn
        exec: drop_resp

  - tag: query_gfw
    type: sequence
    args:
      - exec: $dns_nocn

  - tag: query_fallback
    type: sequence
    args:
      - exec: $ecs
      - exec: prefer_ipv4
      - exec: $fallback_seq

  - tag: query_lan
    type: sequence
    args:
      - exec: $cache_lan
      - matches: has_resp
        exec: return
      - exec: $ecs
      - exec: $local_seq

  - tag: query_other
    type: sequence
    args:
      - exec: $ecs
      - exec: $other_seq

  - tag: pre_handle
    type: sequence
    args:
      - exec: $ttl_1h
      - exec: accept

  - tag: main_handle
    type: sequence
    args:
      - exec: $ttl_5m
      - exec: accept

  # pre_sequence 结果处理 
  - tag: has_resp_pre
    type: sequence
    args:
      - matches: has_resp # 如果 pre 序列已有响应
        exec: goto pre_handle

  # main_sequence 结果处理
  - tag: has_resp_main
    type: sequence
    args:
      - matches: has_resp
        exec: goto main_handle

  - tag: reject_null_domain
    type: sequence
    args:
      - exec: query_summary reject_null_domain

  - tag: reject_qtype65
    type: sequence
    args:
      - exec: query_summary reject_qtype65

  - tag: reject_ad
    type: sequence
    args:
      - exec: query_summary reject_adlist

  # pre_sequence
  - tag: pre_sequence
    type: sequence
    args:
      - matches: qtype 65 # TYPE 65 类型|DNS服务器状态
        exec: $reject_qtype65
      - matches: "qname keyword::" # 无效域名
        exec: $reject_null_domain
      - matches: qtype 12 # TYPE 12 类型|反查域名 PTR 记录
        exec: $query_other
      - matches: qtype 255 # TYPE 255 类型|DNS服务器拓展支持
        exec: $query_other

  # main_sequence
  - tag: main_sequence
    type: sequence
    args:
      - matches: qname $geosite_ads-all # ad 域名
        exec: $reject_ad
      - exec: $cache_wan # cache wan
      - exec: jump has_resp_main
      - matches: qname $geosite_cn # cn 域名
        exec: $query_cn
      - exec: jump has_resp_main
      # 检查是否符合GFW域名规则
      - matches: qname $geosite_gfw
        exec: $query_gfw
      - exec: jump has_resp_main
      - matches: qname $geosite_location-!cn # 非 cn 域名
        exec: $query_nocn
      - exec: jump has_resp_main
      # 其他
      - exec: $ecs
      - exec: $query_fallback
      - exec: jump has_resp_main

  - tag: sequence
    type: sequence
    args:
      - exec: metrics_collector metrics
      - exec: $pre_sequence
      - exec: $main_sequence

  # 在同一端口启动 udp 和 tcp 服务器。
  - type: udp_server
    args:
      entry: sequence
      listen: :53