plugins:
  ################# 预加载插件 ################
  - tag: alidnsdnspod
    type: forward
    args:
      concurrent: 2  # 减少并发查询数
      upstreams:
        - addr: "udp://223.5.5.5"
        - addr: "udp://223.6.6.6"
        - addr: "udp://119.29.29.29"
        - addr: "udp://119.28.28.28"

  - tag: trafficroute
    type: forward
    args:
      concurrent: 1  # 减少并发查询数
      upstreams:
        - addr: "udp://180.184.1.1"
        - addr: "udp://180.184.2.2"

  - tag: quad9
    type: forward
    args:
      concurrent: 1  # 减少并发查询数
      upstreams:
        - addr: "udp://9.9.9.10"
        - addr: "udp://149.112.112.10"

  - tag: cleanbrowsing
    type: forward
    args:
      concurrent: 1  # 减少并发查询数
      upstreams:
        - addr: "udp://185.228.168.168"
        - addr: "udp://185.228.169.168"

  - tag: cache_lan
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 86400

  - tag: cache_wan
    type: cache
    args:
      size: 131072
      lazy_cache_ttl: 86400

  - tag: ecs
    type: ecs_handler
    args:
      forward: true
      preset: 45.207.213.35
      send: false
      mask4: 24
      mask6: 48

  ################# DNS #################
  - tag: dns_nocn
    type: fallback
    args:
      primary: cleanbrowsing
      secondary: quad9
      threshold: 500
      always_standby: true

  - tag: dns_cn
    type: fallback
    args:
      primary: alidnsdnspod
      secondary: trafficroute
      threshold: 200
      always_standby: true

  - tag: dns
    type: fallback
    args:
      primary: dns_cn
      secondary: dns_nocn
      threshold: 200
      always_standby: true

  # 在同一端口启动 udp 和 tcp 服务器。
  - type: udp_server
    args:
      entry: dns
      listen: :53